### ISSUE TITLE
look into building for deploying on pip

### ISSUE THREAD

**Issue by allohakdan** [mrdanbrooks/minibus#12]
One of the goals of minibus is to contain everything inside a single python module (.py) file. This allows it to be easily included in a project simply by dropping the one file along side your other source files without needing to install system-wide software or messing with package paths.

However, there are some reasons why it would be good to also package the software
- Installing the software makes sure different projects are all using the same version of minibus protocol
- Installations are easily upgraded to higher versions
- Installed scripts (such as mbtt) can be run from anywhere, not just one directory

Currently, we have a debian installer that does this for us. It would be nice to look at something more cross distribution/platform, such as pip!

**Comment by allohakdan** [comment]
The Debian packaging is nice, but only lets you install on debian. 
- The python installing will allow for more flexible installing across platforms (Unix and OSX at least).
- Will allow for using in python virtualenv's
- Will allow for installing from local package with pip
- Could be posted to pypi for other people to easily install

Packaging Guide
https://python-packaging-user-guide.readthedocs.org/en/latest/

Sample Packaged Project
https://github.com/pypa/sampleproject

We can test deploy using the learning site for pypi that gets cleaned regularly
https://testpypi.python.org/pypi

**Comment by mrdanbrooks** [comment]
successfully deployed! Twisted and GnuPG are not required dependencies however.
